version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  exclusions:
    paths:
      - conf
      - mock
      - test
      - tests
      - clients
      - example
      - ".*\\.generated\\.go$"
      - ".*\\.gen\\.go$"
      - ".*\\.mock\\.go$"
      - ".*\\.thrift\\.go$"
  enable:
    - bodyclose     # checks whether HTTP response body is closed successfully
    - errcheck      # checking for unchecked errors in go programs
    - staticcheck   # go vet on steroids, applying a ton of static analysis checks
    - unused        # checks Go code for unused constants, variables, functions and types
    - unparam       # finds unused function parameters
    - goconst       # finds repeated strings that could be replaced by a constant
    - govet         # examines Go source code and reports suspicious constructs
    - ineffassign   # detects when assignments to existing variables are not used
    - dogsled       # for Go source code that specializes in simplifying a code
    - misspell      # finds commonly misspelled English words in comments
