run_server:
	OTEL_TRACES_EXPORTER=console OTEL_METRICS_EXPORTER=console go run server/main.go -conf=server/conf.yaml

run_client:
	OTEL_TRACES_EXPORTER=console OTEL_METRICS_EXPORTER=console go run client/main.go -conf=client/conf.yaml
